package:
  name: simp_tools
  version: 0.1.1.1

source:
  git_url: https://github.com/dsimpson1980/simp_tools.git

#build:
#  script: python setup.py sdist

requirements:
  build:
    - python
    - setuptools
    - distribute
    - pandas
    - pyyaml
  run:
    - python
    - pandas

test:
  files:
    - simp_tools
  requires:
    - nose
    - pyyaml
  imports:
    - simp_tools
  commands:
    - nosetests

about:
  license: MIT